{
 "title": "SLO's",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Create product time in seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "create_product_seconds_sum / create_product_seconds_count",
     "legendFormat": "Create product time in seconds"
    }
   ]
  },
  {
   "title": "Login success rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(login_success[30d]) / (rate(login_attempt[30d]) + rate(login_success[30d]))",
     "legendFormat": "Login success rate"
    }
   ]
  },
  {
   "title": "Request success rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{status_code!~\"5.+\"}[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "Request success rate"
    }
   ]
  }
 ]
}